<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>wsg_50_simulation</name>
  <version>0.0.0</version>
  <description>The wsg_50_simulation package</description>

  <maintainer email="nalt@todo.todo">nalt</maintainer>

  <license>BSD</license>

  <author>Nicolas Alt</author>
  <author>Robotnik</author>
  <author>Weiss Robotics</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>urdf</depend>
  <depend>sensor_msgs</depend>
  <depend>wsg_50_common</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
